services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Theme\Lisa\:
        resource: '../../**'
        exclude:
            - '../../Resources/**'
            - '../../Theme.php'
